xychart-beta
    title "从开篇论文到第一次进入标准的年数"
    x-axis ["无人机", "非正交多址", "毫米波", "大规模MIMO", "Turbo", "Polar", "深度学习物理层", "LDPC", "MIMO", "通感", "全双工", "OFDM"]
    y-axis "年" 0 --> 26
    bar [2, 3, 4, 5, 6, 7, 8, 9, 12, 14, 15, 24]
