# -*- coding: utf-8 -*-
# B 组标注规格（28 张）：第一部 p1-01-0 … p1-09-2，第二部 p2-01-0 … p2-07-2。
# 数据、序列顺序、坐标范围一律取图源；这里只给标题、轴名、图例、刻度与版式。
REF = 'ref'
MINUS = '−'

OV = {
 # ---------------- 第一部 ----------------
 'p1-01-0': dict(
     title='位置无知：定位误差让相位预测失去相干',
     xlabel=r'位置误差标准差 $\sigma_d$（mm）',
     ylabel='平均相干度',
     legend=[r'3.5 GHz（$\lambda\approx8.6$ cm）', r'28 GHz（$\lambda\approx1.07$ cm）', '相干度 0.9'],
     colors=[0, 1, REF], styles=['-', '-', '--'],
 ),
 'p1-02-1': dict(
     title=r'Fresnel 反射系数随入射角变化（$\varepsilon_r=5$，无耗）',
     xlabel=r'入射角 $\theta_i$（度）',
     ylabel=r'反射系数 $\Gamma$',
     legend=[r'垂直极化 $\Gamma_{\perp}$', r'平行极化 $\Gamma_{\parallel}$', '零线'],
     colors=[0, 1, REF], styles=['-', '-', '--'],
 ),
 'p1-03-0': dict(
     title=r'低于门限的深衰概率：瑞利、莱斯与 Nakagami-$m$',
     xlabel='门限（相对平均功率，dB）',
     ylabel='概率',
     ylog10=True,
     legend=['瑞利', r'莱斯 $K=6$ dB', r'莱斯 $K=10$ dB', r'Nakagami $m=3$'],
 ),
 'p1-04-0': dict(
     title=r'空间相关函数：三维 $\mathrm{sinc}$ 与二维 $J_0$',
     xlabel=r'两点间距 $d/\lambda$',
     ylabel='相关系数',
     legend=[r'三维 $\mathrm{sinc}(2d/\lambda)$', r'二维 $J_0(2\pi d/\lambda)$', '零线'],
     colors=[0, 1, REF], styles=['-', '-', '--'],
 ),
 'p1-04-3': dict(
     title=r'Landau 相变：特征值在 $N_0=2L/\lambda$ 附近陡降',
     xlabel=r'特征值序号 $n$',
     ylabel=r'特征值 $\mu_n$',
     legend=[r'$L=10\lambda$（$N_0=20$）', r'$L=5\lambda$（$N_0=10$）', '0.5 水平线'],
     colors=[0, 1, REF], styles=['-', '-', '--'],
 ),
 'p1-05-1': dict(
     title=r'发散的渐近级数：误差先降后升（$x=10$）',
     xlabel=r'截断项数 $N$',
     ylabel='误差',
     ylog10=True, ylog10_step=1,
     xticks=([1, 5, 10, 15, 20], ['1', '5', '10', '15', '20']),
     markers='o',
     legend=[r'前 $N$ 项部分和的误差', r'舍去的下一项 $N!/x^N$'],
 ),
 'p1-06-1': dict(
     title=r'对数稳定性：数据误差换重建误差的汇率（$\delta=1/2$）',
     xlabel=r'数据精度 $-\log_{10}\epsilon$',
     ylabel='重建误差（常数取 1）',
     legend=[r'对数稳定 $|\ln\epsilon|^{-1/2}$', r'0.19（$10^{-3}$ 处误差之半）', r'Lipschitz 级 $C\epsilon$'],
     colors=[0, REF, 1], styles=['-', '--', '-'], markers=['o', None, 'o'],
 ),
 'p1-07-1': dict(
     title=r'单邻居预测误差随测点距离回升（$\beta=20$ m）',
     xlabel=r'测点到目标点距离 $d$（m）',
     ylabel='均方根误差（dB）',
     legend=[r'单邻居 $\sqrt{\mathrm{MSE}(d)}$', '不建地图（纯路损）', r'多径地板 $\sigma=3$ dB'],
     colors=[0, REF, REF], styles=['-', '--', ':'],
 ),
 'p1-08-2': dict(
     title=r'预测半径：有效数字沿外推距离蒸发（$\alpha(r)=1-r/r_{\max}$）',
     xlabel=r'外推距离 $r/r_{\max}$',
     ylabel=r'保留的相对精度（$-\log_{10}$ 误差）',
     legend=[r'60 dB（$\varepsilon=10^{-3}$）', r'120 dB（$\varepsilon=10^{-6}$）'],
 ),
 'p1-09-1': dict(
     title='CKM 的香农曲线：两个端点已知，中段空白',
     xlabel=r'环境描述率 $R_{\mathrm{env}}$（比特，对数刻度）',
     ylabel=r'容量增益 $\Delta C$（bit/s/Hz）',
     legend=['凹增', '阈值跳变', '早饱和'],
     styles=['--', '--', '--'],          # 正文称这三条为"虚线"（假想的中段）
 ),
 'p1-09-2': dict(
     title=r'普适性相图：$N_{\mathrm{eff}}$ 决定环境知识的汇率',
     q={1: '过渡区\n$K$ 因子升高',
        2: '几何确定区\n$N_{\\mathrm{eff}}\\lesssim 1$，汇率最高',
        3: '过渡区\n径少但看不清',
        4: '瑞利/MP 普适区\n$N_{\\mathrm{eff}}\\gg 1$，汇率最低'},
     qpos={2: (0.25, 0.70, 'center', 'center'), 4: (0.75, 0.29, 'center', 'center')},
     poff={'太赫兹 大带宽超大孔径': (8, 0, 'left', 'center'),
           'mmWave 400MHz 256 阵元': (8, 0, 'left', 'center')},
 ),
 # ---------------- 第二部 ----------------
 'p2-01-0': dict(
     title='当代场景在"两种退化 × 两种知识"平面上的位置',
     q={1: '耐用品被设错\n泛化理论的地盘',
        2: '耐用品被粗化\n排序与格的地盘',
        3: '易逝品被压缩\n亏格与预算的地盘',
        4: '易逝品被误读\n失配译码的地盘'},
     qpos={3: (0.25, 0.31, 'center', 'center')},
     poff={'ISAC 感知辅助波束管理': (0, 8, 'center', 'bottom'),
           '语义 / 目标导向通信': (-6, 8, 'left', 'bottom')},
 ),
 'p2-01-1': dict(
     title=r'1 dB 的 NMSE 改善值多少 bps/Hz（$M=4$，ZF+RVQ）',
     xlabel='反馈重建误差 NMSE（dB）',
     ylabel='边际汇率（bps/Hz per dB）',
     xticklabels=[MINUS + '50', MINUS + '40', MINUS + '30', MINUS + '20', MINUS + '10', '0'],
     legend=[r'$P=20$ dB', r'$P=30$ dB'],
 ),
 'p2-02-1': dict(
     title=r'BEC($\epsilon$) 相对 BSC(0.2) 的三项优势（正=BEC 更好），横轴 $\epsilon$',
     xlabel=r'BEC 擦除概率 $\epsilon$',
     ylabel='优势值（BEC 减 BSC）',
     legend=['互信息优势', 'MMSE 优势', '判决优势', '零线'],
     colors=[0, 1, 2, REF], styles=['-', '-', '-', '--'], markers=['o', 'o', 'o', None],
 ),
 'p2-02-2': dict(
     title=r'BEC($\beta$) 与 BSC($\alpha$) 的四段式排序边界（横轴 $\alpha$，纵轴 $\beta$）',
     xlabel=r'BSC 交叉概率 $\alpha$',
     ylabel=r'BEC 擦除概率 $\beta$',
     legend=[r'$\beta=2\alpha$（degraded）', r'$\beta=4\alpha(1-\alpha)$（less noisy）',
             r'$\beta=h(\alpha)$（more capable）', r'算例 $\beta=0.6$'],
     colors=[0, 1, 2, REF], styles=['-', '-', '-', '--'], markers=['o', 'o', 'o', None],
     legend_loc='lower right',
 ),
 'p2-03-1': dict(
     title=r'二元间接率失真：$R(D)=1-h\left(\frac{D-q}{1-2q}\right)$，三条 $q$',
     xlabel=r'对隐变量 $\theta$ 的汉明失真 $D$',
     ylabel=r'速率 $R$（bit / 符号）',
     legend=[r'$q=0.2$', r'$q=0.1$', r'$q=0$（直接压缩）'],
 ),
 'p2-04-0': dict(
     title='拉普拉斯噪声下最近邻译码的失配代价下界（bit / 信道使用）',
     xlabel='SNR（dB）',
     ylabel=r'代价 $\Delta$ 的熵功率下界',
     xticklabels=[MINUS + '10', '0', '10', '20', '30', '40'],
     legend=['熵功率下界', '高 SNR 极限 0.104 bit'],
     colors=[0, REF], styles=['-', '--'], markers=['o', None],
 ),
 'p2-04-1': dict(
     title=r'命题 4.4 的风险界随墙位移 $\delta$ 的变化：$2|\sin(2\pi\delta/\lambda)|$（包络）',
     xlabel=r'墙位移 $\delta$（mm）',
     ylabel=r'$\|\mathbf{h}_\delta-\mathbf{h}_0\|\,/\,|a_1|$',
     legend=[r'3.5 GHz（$\lambda/4=21.4$ mm）', r'28 GHz（$\lambda/4=2.68$ mm）'],
 ),
 'p2-04-2': dict(
     title='环境泛化相图：偏移动了什么 × 模型看的是什么',
     x=[r'偏移只改相位（$\lambda$ 级）', r'偏移连结构也改（$L$ 级）'],
     y=[r'模型依赖相位（$\lambda$ 级特征）', r'模型依赖结构（$L$ 级特征）'],
     q={1: '结构变了 · 模型看结构\n需在线适配 / Case 3 微调',
        2: '只动相位 · 模型看结构\n安全迁移区',
        3: '只动相位 · 模型看相位\n$\\lambda/4$ 边界区',
        4: '结构变了 · 模型看相位\n崩塌区'},
     qpos={2: (0.25, 0.52, 'center', 'bottom')},
     pname={'3GPP Case 2 室内↔室外 CSI 压缩': '3GPP Case 2\n室内↔室外 CSI 压缩',
            'sim-to-real 相位级 CSI（cm 级几何误差）': 'sim-to-real 相位级 CSI\n（cm 级几何误差）',
            '数字孪生运维 · 城市改建 · 相位相干 CKM': '数字孪生运维 · 城市改建 ·\n相位相干 CKM'},
     poff={'sim-to-real 波束预测 / 定位': (-8, 0, 'right', 'center'),
           '同类场景跨厂商（Nokia↔Oppo）CSI 压缩': (0, 8, 'center', 'bottom'),
           '跨厂商同类场景（CATT 跨测）': (-8, 0, 'right', 'center'),
           'sim-to-real 相位级 CSI（cm 级几何误差）': (0, 8, 'center', 'bottom')},
 ),
 'p2-05-0': dict(
     title=r'二元折中示意：联合功率分割曲线 vs 两角点的分时弦（$P=10$）',
     xlabel=r'感知失真 $D$',
     ylabel=r'通信速率 $R$（bit/s/Hz）',
     legend=[r'联合功率分割 $R=\log_2(12-1/D)$', '两角点分时弦'],
     xnumeric=True, xticks=([1/11, 0.25, 0.5, 0.75, 1.0], ['$1/11$', '$0.25$', '$0.5$', '$0.75$', '$1$']),
 ),
 'p2-05-2': dict(
     title='认知平衡点 $\\alpha^\\star$ 随 $\\log_{10}\\Lambda$：\n'
           r'饱和型（$\Delta C_{\max}=0.5$）vs 幂律型（$c=0.5,\ \beta=1/2$）',
     xlabel=r'$\log_{10}\Lambda$',
     ylabel=r'最优感知占比 $\alpha^\star$',
     legend=['饱和型', '幂律型', r'极限 $\beta/(1+\beta)=1/3$'],
     colors=[0, 1, REF], styles=['-', '-', '--'], markers=['o', 'o', None],
 ),
 'p2-05-3': dict(
     title=r'吞吐 $J(\alpha)$ 随感知占比 $\alpha$：饱和型汇率，三组 $\Lambda$',
     xlabel=r'感知占比 $\alpha$',
     ylabel=r'长期吞吐 $J$（$C_0=1$）',
     legend=[r'$\Lambda=10$', r'$\Lambda=100$', r'$\Lambda=1000$'],
 ),
 'p2-05-5': dict(
     title=r'六个应用在"$\Lambda$ 的量级 × 汇率是否饱和"平面上的位置（本站定性定位）',
     x=[r'$\Lambda$ 小：环境快、感知慢', r'$\Lambda$ 大：环境静、感知快'],
     y=[r'汇率早饱和（$\alpha^\star$ 按 $\ln\Lambda/\Lambda$ 消失）', r'汇率持续增长（$\alpha^\star$ 趋于常数）'],
     q={1: '该长期投入感知\n平衡点是常数',
        2: '总值得感知但饱和早\n短期投入',
        3: '知识攒不下\n按易逝品处理',
        4: '一次建库、长期摊销\n$\\alpha^\\star$ 极小'},
     qpos={4: (0.72, 0.25, 'center', 'center')},
     poff={'数字孪生运维同步': (0, 8, 'center', 'bottom'),
           '边缘推理特征缓存': (0, 8, 'center', 'bottom')},
 ),
 'p2-06-1': dict(
     title=r'反相关：格内位置 $s$ 上的增益差、错格概率与两者之积（$\sigma=4.5$ dB）',
     xlabel=r'格内位置 $s$（0 = 波束中心，0.5 = 交叠点）',
     ylabel='dB 或按下方说明缩放',
     legend=[r'增益差 $\Delta(s)$（dB）', r'错格概率 $P_{\mathrm{err}}(s)\times20$',
             r'乘积 $P_{\mathrm{err}}(s)\Delta(s)\times10$'],
 ),
 'p2-06-2': dict(
     title=r'期望错格损失 $\Psi(\sigma)$ 与两种朴素估计（$N=64$ DFT 码本）',
     xlabel=r'增益估计误差 $\sigma$（dB）',
     ylabel='期望错格损失（dB）',
     legend=[r'真实 $\Psi(\sigma)$', r'二阶近似 $\sigma^2/34.74$', r'错格率 $\times\,3.92$ dB'],
 ),
 'p2-06-3': dict(
     title='反注水分配：三个预算项各拿多少比特（锚定链，算例 6.6）',
     xlabel=r'总预算 $B$（比特）',
     ylabel=r'该项分到的比特 $b_i$',
     legend=['材质项', '几何项', '增益量化项'],
 ),
 'p2-07-1': dict(
     title=r'三条候选 Q3 形状给出的认知平衡点 $\alpha^\star$（横轴 $\log_{10}\Lambda$）',
     xlabel=r'$\log_{10}\Lambda$',
     ylabel=r'最优感知占比 $\alpha^\star$',
     legend=[r'阈值跳变 $1/\Lambda$', '早饱和', '凹增'],
     yscale='log', ylim=(5e-5, 0.6),
     yticks=([1e-4, 1e-3, 1e-2, 1e-1], ['$10^{-4}$', '$10^{-3}$', '$10^{-2}$', '$10^{-1}$']),
 ),
 'p2-07-2': dict(
     title='本部子问题的 AI 适配性：形式化共识 × 证明链长度',
     q={1: '长链条 · 陈述精确\nAI 甜点区',
        2: '长链条 · 定义未定\n先由人钉死',
        3: '短链条 · 定义未定\n概念工作',
        4: '短链条 · 陈述精确\n直接做'},
     pname={'A2 δk 阶梯': r'A2 $\delta_k$ 阶梯',
            'C1 K 反射面界': r'C1 $K$ 反射面界',
            'D1 ΔC 第一组数': r'D1 $\Delta C$ 第一组数',
            '猜想 1.3 的 ρ 与可加性': r'猜想 1.3 的 $\rho$ 与可加性',
            '定理三全形（绕射 · 遮挡 · Lip）': r'定理三全形（绕射 · 遮挡 · $\mathrm{Lip}$）',
            '定理二全形（任务类 converse）': '定理二全形\n（任务类 converse）'},
     qpos={4: (0.62, 0.26, 'center', 'center')},
     poff={'A1 码本族亏格表': (-8, 0, 'right', 'center'),
           'Q5.3 POMDP 稳态极限': (-8, 0, 'right', 'center'),
           '定理二全形（任务类 converse）': (-8, 0, 'right', 'center')},
 ),
}
