# -*- coding: utf-8 -*-
# C 组标注规格：第三部 9 张 + 第四部 21 张。数据一律取自 charts/src/<id>.mmd，这里只管标注。
OV = {
 # ---------------- 第三部 ----------------
 'p3-01-1': dict(
     title='滑雪租赁的价目表：确定性算法的一致性与鲁棒性',
     xlabel=r'信任旋钮 $\lambda$（越小越信任预测）',
     ylabel='竞争比',
     legend=[r'一致性 $1+\lambda$', r'鲁棒性下界 $1+1/\lambda$'],
 ),
 'p3-02-3': dict(
     title=r'一长 $n$ 短网络：把 $\alpha$ 从效率拧到公平（$c=1$）',
     xlabel=r'公平参数 $\alpha$（按对数等距排开）',
     ylabel='速率',
     xticklabels=['$1/4$', '$1/2$', '$1$', '$2$', '$4$', '$8$', '$16$'],
     legend=[r'总吞吐 $2-x_0^\star$，$n=2$', r'长流速率 $x_0^\star$，$n=2$', r'长流速率 $x_0^\star$，$n=10$'],
 ),
 'p3-03-1': dict(
     title=r'$a=1.5$、$p_2=1$ 时沿 $p_1$ 的一维切片：两端各一个峰',
     xlabel=r'$p_1$',
     ylabel=r'和速率 $f$',
 ),
 'p3-03-2': dict(
     title=r'$a=1$ 扫 SNR：独占与全开在 $\varphi$ 处交叉',
     xlabel='SNR（dB）',
     ylabel='顶点处的和速率',
     legend=[r'独占 $\log_2(1+P)$', r'全开 $2\log_2\!\left(1+\frac{P}{P+1}\right)$'],
 ),
 'p3-04-3': dict(
     title=r'$V$ 的双对数折中：超额能耗与时延（算例参数）',
     xlabel=r'$V$（按对数等距排开）',
     ylabel='能耗超额（%）/ 时延（ms）',
     ylog10=True, ylog10_step=1,
     legend=['能耗超额（%）', r'时延（ms），$\varepsilon=0.2$', r'时延（ms），$\varepsilon=0.02$'],
 ),
 'p3-05-2': dict(
     title='算例 B：前视窗口买到的先知间隙',
     xlabel=r'前视 $w$（时隙；4 以后间距不等）',
     ylabel='捕获先知间隙的比例（%）',
 ),
 'p3-06-4': dict(
     title=r'两小区 $C(\varepsilon)$ 的构造性上界与 TL 一维协议：同一个斜率',
     xlabel=r'目标精度 $\varepsilon$',
     ylabel='交换的比特数',
     xticklabels=['$1$', '$0.1$', '$0.01$', '$10^{-3}$', '$10^{-4}$', '$10^{-5}$', '$10^{-6}$'],
     legend=[r'本节上界 $4\lceil\log_2(2L_WD/\varepsilon)\rceil$', r'TL 一维协议 $4\log_2(1/\varepsilon)$'],
 ),
 'p3-07-1': dict(
     title=r'批处理的分层代价 $\mathrm{PoL}(K)$：固定开销 $T_0$ 决定天花板',
     xlabel=r'批量 $K$（按对数等距排开）',
     ylabel=r'$\mathrm{PoL}$（分层时长 ÷ 联合时长）',
     legend=[r'$T_0=50$ ms', '上限 26', r'$T_0=10$ ms', '上限 6'],
     colors=[0, 'ref', 1, 'ref'], styles=['-', '--', '-', '--'], markers=['o', None, 'o', None],
 ),
 'p3-08-1': dict(
     title=r'反向蝴蝶上的 $q$ 元算术和：计算割集界随字母表爬向 2',
     xlabel=r'字母表大小 $q$（按对数等距排开）',
     ylabel='每使用一次网络算出的和数',
     legend=[r'计算割集界 $2/\log_q(2q-1)$', '极限 2（割容量用满）', '路由与线性码：1'],
     colors=[0, 'ref', 'ref'], styles=['-', '--', ':'], markers=['o', None, None],
 ),
 # ---------------- 第四部 ----------------
 'p4-01-0': dict(
     title=r'仿射代价曲线与两条非线性水平线（$k=0.2$, $\sigma=5$）',
     xlabel=r'仿射增益 $t$（$x_1=tx_0$）',
     ylabel=r'总代价 $J$',
     legend=[r'仿射策略 $J_{\mathrm{aff}}(t)$', '1968 一步符号策略', '2017 已知最好上界'],
     styles=['-', '--', '--'], markers=['o', None, None],
 ),
 'p4-01-1': dict(
     title=r'六十年的上界序列（$k=0.2$, $\sigma=5$；纵轴为总代价）',
     xlabel='策略族（按年份与复杂度）',
     ylabel=r'总代价 $J$',
     xticklabels=['仿射', '1步\n1968', '2步\n1999', '2.5步\n2001', '3.5步\n2001', '3.5步\n2009',
                  '4步\n2011', '5步\n2014', '局搜\n2017'],
 ),
 'p4-02-1': dict(
     title=r'分散式团队 vs 集中式的最优代价（$c=1$）',
     xlabel=r'观测噪声标准差 $\eta$',
     ylabel=r'最优期望代价 $J$',
     legend=[r'分散式 $J_{\mathrm{dec}}^\star$', r'集中式 $J_{\mathrm{cent}}^\star$'],
 ),
 'p4-02-2': dict(
     title='分散化代价的相对值（百分比）随观测噪声变化',
     xlabel=r'观测噪声标准差 $\eta$',
     ylabel=r'$J_{\mathrm{dec}}^\star/J_{\mathrm{cent}}^\star-1$（百分比）',
     legend=[r'$c=1$', r'$c=0.1$'],
 ),
 'p4-02-4': dict(
     title='无线场景在嵌套-耦合平面上的位置（定性）',
     q={1: '部分嵌套可达\nRadner 与 Ho-Chu 适用', 2: '非经典深渊\nWitsenhausen 邻域',
        3: '各自为政也无妨', 4: '共享过剩\n话费白花'},
     qpos={3: (0.25, 0.30, 'center', 'center')},
 ),
 'p4-03-2': dict(
     title=r'示意：可实现协作增益份额 $\rho^{2d}$ 随回传时延 $d$（时隙）；上 $\rho=0.9$，下 $\rho=0.7$',
     xlabel=r'回传时延 $d$（时隙）',
     ylabel='增益份额',
     legend=[r'$\rho=0.9$', r'$\rho=0.7$'],
 ),
 'p4-03-3': dict(
     title='信息结构相图（本站提法：已有结果的重排；边界为示意，非已证曲线）',
     x=[r'通信时延 / 耦合时标 $\leq 1$（信息比影响快）', r'通信时延 / 耦合时标 $>1$（影响比信息快）'],
     q={1: '非经典\n结构完整但信息过期，非 QI', 2: 'QI 凸区：定理 3.3、3.6 覆盖',
        3: '非 QI\n补链路可修复，命题 3.11', 4: '深渊\nWitsenhausen 型，离散版 NP-complete'},
     qpos={3: (0.25, 0.25, 'center', 'center'), 4: (0.75, 0.27, 'center', 'center')},
     poff={'同站 CoMP-JT 理想回传': (8, 0, 'left', 'center'),
           'O-RAN 近实时 RIC 做时隙级调度': (-8, 0, 'right', 'center'),
           'D2D 无回传': (-8, 0, 'right', 'center'),
           'Witsenhausen 反例': (-8, 0, 'right', 'center')},
 ),
 'p4-04-0': dict(
     title=r'协调价签：最小速率 $R=1-h(\epsilon)$ 随允许的坏时隙率 $\epsilon$',
     xlabel=r'允许的坏时隙率 $\epsilon$',
     ylabel='比特 / 时隙',
     legend=[r'最小速率 $R^\star=1-h(\epsilon)$', '直接告知：1 比特/时隙'],
     colors=[0, 'ref'], styles=['-', '--'], markers=['o', None],
 ),
 'p4-04-1': dict(
     title='话费—代价曲线：坏时隙率随回传预算下降（下：真实曲线；上：线性参照）',
     xlabel=r'回传预算 $R$（比特 / 时隙）',
     ylabel='最小坏时隙率',
     legend=[r'真实曲线 $\epsilon^\star(R)=h^{-1}(1-R)$', '线性参照'],
     colors=[0, 'ref'], styles=['-', '--'], markers=['o', None],
 ),
 'p4-05-1': dict(
     title=r'每轮期望产出 token 数随接受率 $\beta$（自下而上 $\gamma=2,4,8$）',
     xlabel=r'接受率 $\beta=1-\mathrm{TV}(p,q)$',
     ylabel='期望产出（token / 轮）',
     legend=[r'$\gamma=2$', r'$\gamma=4$', r'$\gamma=8$'],
 ),
 'p4-05-2': dict(
     title=r'期望加速 $S$ 随接受率 $\alpha$（$\gamma=7$；自上而下 $c=0,0.05,0.2$）',
     xlabel=r'期望接受率 $\alpha$',
     ylabel=r'加速倍数 $S$',
     legend=[r'$c=0$', r'$c=0.05$', r'$c=0.2$'],
 ),
 'p4-06-0': dict(
     title='同一个抢频带博弈，三个学习率下的轨迹',
     xlabel=r'时隙 $t$',
     ylabel='选频带 A 的概率',
     legend=[r'$\eta=4$', r'$\eta=9$', r'$\eta=13$'],
 ),
 'p4-06-1': dict(
     title='分岔图：吸引子的上下包络随学习率变化',
     xlabel=r'有效学习率 $\eta$',
     ylabel='选频带 A 的概率',
     legend=['上包络（最大值）', '下包络（最小值）'],
 ),
 'p4-06-2': dict(
     title='学习动力学相图（本站提法）',
     q={1: '混沌 / 发散\n末迭代不可预测', 2: '极限环与 Li-Yorke\n时间平均仍对',
        3: '收敛到纯 Nash\n（定理 6.5 / 6.8）', 4: '循环\n时间平均收敛，末迭代不收敛'},
     qpos={3: (0.25, 0.32, 'center', 'center')},
 ),
 'p4-07-1': dict(
     title=r'有限 $N$ 的对称 Nash 解如何爬向平均场解（相对 $u^{\mathrm{MFG}}$ 的百分比）',
     xlabel=r'$\log_{10}N$（$N=1,10,100,1000,10000$）',
     ylabel=r'$u$ 相对 $u^{\mathrm{MFG}}$（%）',
     legend=[r'有限 $N$ 精确 Nash $u^{(N)}$', 'MFG（100%）', 'MFC（66.67%）'],
     styles=['-', '--', '--'], markers=['o', None, None],
 ),
 'p4-07-2': dict(
     title=r'三个尺度：只有一条不随 $N$ 衰减（百分比，$\theta=1,\beta=0.5,\lambda=0.5,\sigma=0.3$）',
     xlabel=r'$\log_{10}N$（$N=10,100,1000,10000$）',
     ylabel='偏离（%）',
     legend=['MFG$-$MFC 代价差 $O(1)$', r'经验均值涨落 $\propto 1/\sqrt{N}$', r'有限 $N$ 纳什偏差 $\propto 1/N$'],
 ),
 'p4-07-3': dict(
     title='平均场的适用区：横轴耦合有效人数，纵轴个体异质性',
     x=[r'耦合局域（$N_{\mathrm{eff}}$ 常数级）', r'耦合全局（$N_{\mathrm{eff}}$ 与 $N$ 同阶）'],
     y=['个体同质（单类型）', r'个体异质（类型数随 $N$ 增长）'],
     q={1: '多类型平均场\n$K$ 组固定点，可解但维数涨', 2: '平均场失效区\n既没有大数，也没有对称',
        3: '图上博弈 / graphon\n要按图重做，不能用 $1/N$', 4: '经典平均场适用区\n定理 7.1、7.5 的正确战场'},
     qpos={3: (0.25, 0.27, 'center', 'center')},
     pname={'密集小区功控 α=3.7': r'密集小区功控 $\alpha=3.7$'},
     poff={'大规模星座调度': (-8, 0, 'right', 'center'), '密集小区功控 α=3.7': (0, 7, 'center', 'bottom')},
 ),
 'p4-08-1': dict(
     title='Etkin 场景 (d)：均衡速率封顶，正交速率无限增长',
     xlabel=r'发射功率 $P$（dB）',
     ylabel='两系统和速率（b/s/Hz）',
     legend=['唯一 Nash（全展开）', r'正交分带 $\log_2(1+2P)$'],
 ),
 'p4-08-3': dict(
     title='Wyner 线性模型：每小区平均谱效在涨，簇边缘谱效已经封顶',
     xlabel=r'协作簇大小 $K$（连续小区数）',
     ylabel='高功率极限谱效（b/s/Hz/小区）',
     legend=[r'每小区平均，$\alpha=0.2$', r'每小区平均，$\alpha=0.5$', r'簇边缘小区，$\alpha=0.2$',
             r'Lozano 六边形 $K=3$：2.54'],
     colors=[0, 1, 2, 'ref'], styles=['-', '-', '-', '--'], markers=['o', 'o', 'o', None], legend_loc='upper left',
 ),
 'p4-09-1': dict(
     title='Wyner 模型边缘用户谱效随簇大小（$\\alpha=0.2$）：\n无开销单调饱和，含 1% 开销有内点最优',
     xlabel=r'簇大小 $K$',
     ylabel='谱效（b/s/Hz）',
     legend=[r'无开销 $\log_2(1+1/\kappa_1)$', r'含 1% 开销 $C_\tau(K)$'],
 ),
 'p4-09-2': dict(
     title='本部子问题的 AI 适配性：形式化共识 × 证明链长度（本站定性定位）',
     q={1: '长链条 · 陈述精确\nAI 甜点区', 2: '长链条 · 定义未定\n先由人钉死',
        3: '短链条 · 定义未定\n概念工作', 4: '短链条 · 陈述精确：直接做'},
     pname={'T2-a K=3 链式内外界': r'T2-a $K=3$ 链式内外界',
            'T4-a Lozano 模型 κ 对照': r'T4-a Lozano 模型 $\kappa$ 对照',
            'T4-c κ 三候选对照': r'T4-c $\kappa$ 三候选对照',
            'T2-c 猜想 2.6 的 J 闭式': r'T2-c 猜想 2.6 的 $J^\star(R)$ 闭式'},
     qpos={1: (0.89, 0.78, 'center', 'center'), 4: (0.75, 0.025, 'center', 'bottom')},
     poff={'T1-a QI 判定与相图绘制': (-8, 0, 'right', 'center'),
           'T2-a K=3 链式内外界': (-8, 0, 'right', 'center'),
           'T3-a 数值分岔与 Lyapunov': (-8, 0, 'right', 'center'),
           'T4-a Lozano 模型 κ 对照': (-8, 0, 'right', 'center'),
           'T2-b 猜想 5.10 单符号 LP': (-8, 0, 'right', 'center'),
           'T4-b 两类型平均场闭式': (8, 0, 'left', 'center'),
           'T2-c 猜想 2.6 的 J 闭式': (-8, 0, 'right', 'center'),
           'T1-b 三节点链可近似相': (8, 0, 'left', 'center'),
           'T2-d 多方 DISJ 归约': (8, 0, 'left', 'center'),
           'T3-b 观测噪声轴方向': (-8, 0, 'right', 'center'),
           'T4-c κ 三候选对照': (-8, 0, 'right', 'center')},
 ),
}
